<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-28T13:53:53 IST" name="Suite" finished-at="2023-06-28T13:54:25 IST" duration-ms="32356">
    <groups>
    </groups>
    <test started-at="2023-06-28T13:53:53 IST" name="Test" finished-at="2023-06-28T13:54:25 IST" duration-ms="32356">
      <class name="tests.LoginFunctionalityTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:53:53 IST" name="launchApplication" finished-at="2023-06-28T13:53:58 IST" duration-ms="5111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Empty_Credentials()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:53:58 IST" name="test_Empty_Credentials" finished-at="2023-06-28T13:53:59 IST" duration-ms="979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Empty_Credentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:53:59 IST" name="tearDown" finished-at="2023-06-28T13:53:59 IST" duration-ms="100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:53:59 IST" name="launchApplication" finished-at="2023-06-28T13:54:02 IST" duration-ms="3258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Failing_Intentionally()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:02 IST" name="test_Failing_Intentionally" finished-at="2023-06-28T13:54:02 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at tests.LoginFunctionalityTest.test_Failing_Intentionally(LoginFunctionalityTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Failing_Intentionally -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:02 IST" name="tearDown" finished-at="2023-06-28T13:54:02 IST" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:02 IST" name="launchApplication" finished-at="2023-06-28T13:54:05 IST" duration-ms="3083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Forgot_Password_Displayed_And_Click()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:05 IST" name="test_Forgot_Password_Displayed_And_Click" finished-at="2023-06-28T13:54:06 IST" duration-ms="836" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Forgot_Password_Displayed_And_Click -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:06 IST" name="tearDown" finished-at="2023-06-28T13:54:06 IST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:06 IST" name="launchApplication" finished-at="2023-06-28T13:54:10 IST" duration-ms="3196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Invalid_Password()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:10 IST" name="test_Invalid_Password" finished-at="2023-06-28T13:54:11 IST" duration-ms="1226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_Password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:11 IST" name="tearDown" finished-at="2023-06-28T13:54:11 IST" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:11 IST" name="launchApplication" finished-at="2023-06-28T13:54:14 IST" duration-ms="3150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Invalid_Username()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:14 IST" name="test_Invalid_Username" finished-at="2023-06-28T13:54:15 IST" duration-ms="1199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_Username -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:15 IST" name="tearDown" finished-at="2023-06-28T13:54:15 IST" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:15 IST" name="launchApplication" finished-at="2023-06-28T13:54:18 IST" duration-ms="3149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Successful_Login_And_Logout()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:18 IST" name="test_Successful_Login_And_Logout" finished-at="2023-06-28T13:54:25 IST" duration-ms="6275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Successful_Login_And_Logout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginFunctionalityTest@1fa1cab1]" started-at="2023-06-28T13:54:25 IST" name="tearDown" finished-at="2023-06-28T13:54:25 IST" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginFunctionalityTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
